version: "3.1"

services:
  springboot:
    image: lukaszwelnicki/breathelive:latest
    restart: always
    container_name: breathelive
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: breathelive_mongo
    ports:
      - 27017:27017
    volumes:
    - $HOME/data/springboot-mongo-data/breathelive:/data/db
    - $HOME/data/springboot-mongo-bkp/breathelive:/data/bkp
    restart: always
